/** WARNING: This file is automatically generated by plate.
 *  Do not edit this file if you plan on using plate to continue to
 *  generate template files. If you run plate on your templates again,
 *  all changes to this file will be lost!
 */
App.Templates || (App.Templates = {});

App.Templates.foo = function(foo){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
__p+='\n\n<div id=\'foo\'>\n  <h2>Foo</h2>\n\n  <a href=\'/\'>Home</a>\n\n  <div>'+
((__t=( foo.home ))==null?'':__t)+
'</div>\n</div>\n';
return __p;
};

App.Templates.layout = function(data){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
__p+='<!doctype html>\n<html>\n  <head>\n    <title>'+
((__t=( data.title ))==null?'':__t)+
'</title>\n  </head>\n\n  <body>\n    <header>\n      <h1>'+
((__t=( data.page_title ))==null?'':__t)+
'</h1>\n    </header>\n\n    <div id=\'content\'>\n      '+
((__t=( data.content ))==null?'':__t)+
'\n    </div>\n\n    <footer>\n      &copy; 2013 Paul Harper\n    </footer>\n  </body>\n</html>\n';
return __p;
};

