/** WARNING: This file is automatically generated by plank.
*   Do not edit this file if you plan on using plank to continue to
*   generate template files. If you run plank on your templates again,
*   all changes to this file will be lost!
*/
window.Templates || (window.Templates = {});
window.Templates.foo = _.template(
  "\n<div id='foo'>\n  <h2>Foo</h2>\n\n  <a href='/'>Home</a>\n</div>\n"
);
window.Templates.layout = _.template(
  "<!doctype html>\n<html>\n  <head>\n    <title><%= title %></title>\n  </head>\n\n  <body>\n    <header>\n      <h1><%= page_title %></h1>\n    </header>\n\n    <div id='content'>\n      <%= content %>\n    </div>\n\n    <footer>\n      &copy; 2013 Paul Harper\n    </footer>\n  </body>\n</html>\n"
);
