// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  typeof global === 'undefined' && (window.global = window);

  global.Templito = {
    View: {}
  };

  _.templateSettings = {
    evaluate: /<%([\s\S]+?)%>/g,
    interpolate: /<%=!([\s\S]+?)%>/g,
    escape: /<%=(?!!)([\s\S]+?)%>/g
  };

  $(document).ready(function() {
    return $(document.body).html((new Templito.View.HomeView).el);
  });

}).call(this);
