/** WARNING: This file is automatically generated by plank.
*   Do not edit this file if you plan on using plank to continue to
*   generate template files. If you run plank on your templates again,
*   all changes to this file will be lost!
*/
window.Templates || (window.Templates = {});
window.Templates.Bar || (window.Templates.Bar = {});
window.Templates.Bar.baz = _.template(
  "\n<div id='baz'>\n  <h2>Baz</h2>\n</div>\n"
);
window.Templates.Bar.gondolas = _.template(
  "\n<ul>\n  <li><strong>I don't have anything to write</strong></li>\n  <li><%= something_interesting %></li>\n</ul>\n"
);
