/* WARNING: This file was automatically generated by templito.
 * Do not manually edit this file if you plan to continue using templito.
 */
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['exports'], factory);
    } else if (typeof exports === 'object') {
        // CommonJS
        factory(exports);
    } else {
        // Browser globals
        factory((root.App = {}));
    }
}(this, function (exports) {
var App = exports
