/* WARNING: This file was automatically generated by templito.
 * Do not manually edit this file if you plan to continue using templito.
 */

Templito.Template || (Templito.Template = {});

Templito.Template.layout = function(data){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
__p+='\n\n<header>\n  <h1>Templito</h1>\n  <nav>\n    <ul>\n      ';
 _.each(data.nav, function (item) { 
__p+='\n        <li><a href="'+
((__t=(! encodeURI(item.href) ))==null?'':__t)+
'">'+
((__t=( item.name ))==null?'':__t)+
'</a></li>\n      ';
 }); 
__p+='\n    </ul>\n  </nav>\n</header>\n\nMoar stuff\n';
return __p;
};

