// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  Templito.View.HomeView = Backbone.View.extend({
    tagName: 'div',
    initialize: function() {
      this.$el = $(this.el);
      return this.render();
    },
    render: function() {
      return this.$el.html(Templito.Template.layout({
        nav: [
          {
            name: 'Home',
            href: '/'
          }, {
            name: 'Github',
            href: 'https://github.com/benekastah/templito'
          }
        ]
      }));
    }
  });

}).call(this);
